spring:
  h2:
    console:
      path: /h2
  datasource:
    url: jdbc:h2:file:./db/forum
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always